"""Initial revision

Revision ID: 110d69d2aa6f
Revises: 
Create Date: 2024-11-30 08:19:14.221378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110d69d2aa6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orgStructureoOne', sa.String(length=100), nullable=False),
    sa.Column('funcBlock', sa.String(length=100), nullable=False),
    sa.Column('orgStructureTwo', sa.String(length=100), nullable=True),
    sa.Column('orgStructureThree', sa.String(length=100), nullable=True),
    sa.Column('orgStructureFour', sa.String(length=100), nullable=True),
    sa.Column('post', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
